// <auto-generated />
namespace GISCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v_Data_AR_string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v_Data_AR_string));
        
        string IMigrationMetadata.Id
        {
            get { return "201909071633130_v_Data_AR_string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
