//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GISCore.WCF_Suporte {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosUsuario", Namespace="http://starscloud.com.br/services")]
    [System.SerializableAttribute()]
    public partial class DadosUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultSTARSServices", Namespace="http://starscloud.com.br/services")]
    [System.SerializableAttribute()]
    public partial class FaultSTARSServices : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetalhesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Detalhes {
            get {
                return this.DetalhesField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalhesField, value) != true)) {
                    this.DetalhesField = value;
                    this.RaisePropertyChanged("Detalhes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://starscloud.com.br/services", ConfigurationName="WCF_Suporte.Suporte")]
    public interface Suporte {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://starscloud.com.br/services/Suporte/SalvarFotoPerfil", ReplyAction="http://starscloud.com.br/services/Suporte/SalvarFotoPerfilResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GISCore.WCF_Suporte.FaultSTARSServices), Action="http://starscloud.com.br/services/Suporte/SalvarFotoPerfilFaultSTARSServicesFault" +
            "", Name="FaultSTARSServices")]
        void SalvarFotoPerfil(GISCore.WCF_Suporte.DadosUsuario usuario, string conteunoBase64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://starscloud.com.br/services/Suporte/SalvarFotoPerfil", ReplyAction="http://starscloud.com.br/services/Suporte/SalvarFotoPerfilResponse")]
        System.Threading.Tasks.Task SalvarFotoPerfilAsync(GISCore.WCF_Suporte.DadosUsuario usuario, string conteunoBase64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://starscloud.com.br/services/Suporte/BuscarFotoPerfil", ReplyAction="http://starscloud.com.br/services/Suporte/BuscarFotoPerfilResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GISCore.WCF_Suporte.FaultSTARSServices), Action="http://starscloud.com.br/services/Suporte/BuscarFotoPerfilFaultSTARSServicesFault" +
            "", Name="FaultSTARSServices")]
        byte[] BuscarFotoPerfil(GISCore.WCF_Suporte.DadosUsuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://starscloud.com.br/services/Suporte/BuscarFotoPerfil", ReplyAction="http://starscloud.com.br/services/Suporte/BuscarFotoPerfilResponse")]
        System.Threading.Tasks.Task<byte[]> BuscarFotoPerfilAsync(GISCore.WCF_Suporte.DadosUsuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://starscloud.com.br/services/Suporte/SalvarArquivoNoVault", ReplyAction="http://starscloud.com.br/services/Suporte/SalvarArquivoNoVaultResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GISCore.WCF_Suporte.FaultSTARSServices), Action="http://starscloud.com.br/services/Suporte/SalvarArquivoNoVaultFaultSTARSServicesF" +
            "ault", Name="FaultSTARSServices")]
        string SalvarArquivoNoVault(byte[] conteudo, string pathBase, string extensao, int maxfilesubfolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://starscloud.com.br/services/Suporte/SalvarArquivoNoVault", ReplyAction="http://starscloud.com.br/services/Suporte/SalvarArquivoNoVaultResponse")]
        System.Threading.Tasks.Task<string> SalvarArquivoNoVaultAsync(byte[] conteudo, string pathBase, string extensao, int maxfilesubfolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://starscloud.com.br/services/Suporte/BuscarArquivoDoVault", ReplyAction="http://starscloud.com.br/services/Suporte/BuscarArquivoDoVaultResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GISCore.WCF_Suporte.FaultSTARSServices), Action="http://starscloud.com.br/services/Suporte/BuscarArquivoDoVaultFaultSTARSServicesF" +
            "ault", Name="FaultSTARSServices")]
        byte[] BuscarArquivoDoVault(string pathFolderBase, string remoteFileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://starscloud.com.br/services/Suporte/BuscarArquivoDoVault", ReplyAction="http://starscloud.com.br/services/Suporte/BuscarArquivoDoVaultResponse")]
        System.Threading.Tasks.Task<byte[]> BuscarArquivoDoVaultAsync(string pathFolderBase, string remoteFileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SuporteChannel : GISCore.WCF_Suporte.Suporte, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SuporteClient : System.ServiceModel.ClientBase<GISCore.WCF_Suporte.Suporte>, GISCore.WCF_Suporte.Suporte {
        
        public SuporteClient() {
        }
        
        public SuporteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SuporteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuporteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuporteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SalvarFotoPerfil(GISCore.WCF_Suporte.DadosUsuario usuario, string conteunoBase64) {
            base.Channel.SalvarFotoPerfil(usuario, conteunoBase64);
        }
        
        public System.Threading.Tasks.Task SalvarFotoPerfilAsync(GISCore.WCF_Suporte.DadosUsuario usuario, string conteunoBase64) {
            return base.Channel.SalvarFotoPerfilAsync(usuario, conteunoBase64);
        }
        
        public byte[] BuscarFotoPerfil(GISCore.WCF_Suporte.DadosUsuario usuario) {
            return base.Channel.BuscarFotoPerfil(usuario);
        }
        
        public System.Threading.Tasks.Task<byte[]> BuscarFotoPerfilAsync(GISCore.WCF_Suporte.DadosUsuario usuario) {
            return base.Channel.BuscarFotoPerfilAsync(usuario);
        }
        
        public string SalvarArquivoNoVault(byte[] conteudo, string pathBase, string extensao, int maxfilesubfolder) {
            return base.Channel.SalvarArquivoNoVault(conteudo, pathBase, extensao, maxfilesubfolder);
        }
        
        public System.Threading.Tasks.Task<string> SalvarArquivoNoVaultAsync(byte[] conteudo, string pathBase, string extensao, int maxfilesubfolder) {
            return base.Channel.SalvarArquivoNoVaultAsync(conteudo, pathBase, extensao, maxfilesubfolder);
        }
        
        public byte[] BuscarArquivoDoVault(string pathFolderBase, string remoteFileName) {
            return base.Channel.BuscarArquivoDoVault(pathFolderBase, remoteFileName);
        }
        
        public System.Threading.Tasks.Task<byte[]> BuscarArquivoDoVaultAsync(string pathFolderBase, string remoteFileName) {
            return base.Channel.BuscarArquivoDoVaultAsync(pathFolderBase, remoteFileName);
        }
    }
}
